Basedir = '/storage/maullz/Confidence_Sets_Manuscript/';

outdir  = fullfile(Basedir,'Figures','2D_Figures');

if ~isdir(outdir)
    mkdir(outdir)
end

sim_results_mat = {fullfile(Basedir,'Sim_01_results','30_subjects','Sim_01_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_01_results','60_subjects','Sim_01_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_01_results','120_subjects','Sim_01_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_01_results','240_subjects','Sim_01_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_01_results','480_subjects','Sim_01_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_04_results','30_subjects','Sim_04_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_04_results','60_subjects','Sim_04_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_04_results','120_subjects','Sim_04_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_04_results','240_subjects','Sim_04_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_04_results','480_subjects','Sim_04_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_02_results','30_subjects','Sim_02_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_02_results','60_subjects','Sim_02_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_02_results','120_subjects','Sim_02_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_02_results','240_subjects','Sim_02_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_02_results','480_subjects','Sim_02_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_05_results','30_subjects','Sim_05_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_05_results','60_subjects','Sim_05_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_05_results','120_subjects','Sim_05_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_05_results','240_subjects','Sim_05_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_05_results','480_subjects','Sim_05_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_03_results','30_subjects','Sim_03_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_03_results','60_subjects','Sim_03_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_03_results','120_subjects','Sim_03_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_03_results','240_subjects','Sim_03_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_03_results','480_subjects','Sim_03_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_06_results','30_subjects','Sim_06_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_06_results','60_subjects','Sim_06_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_06_results','120_subjects','Sim_06_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_06_results','240_subjects','Sim_06_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_06_results','480_subjects','Sim_06_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_07_results','30_subjects','Sim_07_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_07_results','60_subjects','Sim_07_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_07_results','120_subjects','Sim_07_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_07_results','240_subjects','Sim_07_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_07_results','480_subjects','Sim_07_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_10_results','30_subjects','Sim_10_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_10_results','60_subjects','Sim_10_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_10_results','120_subjects','Sim_10_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_10_results','240_subjects','Sim_10_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_10_results','480_subjects','Sim_10_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_08_results','30_subjects','Sim_08_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_08_results','60_subjects','Sim_08_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_08_results','120_subjects','Sim_08_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_08_results','240_subjects','Sim_08_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_08_results','480_subjects','Sim_08_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_11_results','30_subjects','Sim_11_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_11_results','60_subjects','Sim_11_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_11_results','120_subjects','Sim_11_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_11_results','240_subjects','Sim_11_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_11_results','480_subjects','Sim_11_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_09_results','30_subjects','Sim_09_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_09_results','60_subjects','Sim_09_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_09_results','120_subjects','Sim_09_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_09_results','240_subjects','Sim_09_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_09_results','480_subjects','Sim_09_480_subjects.mat'); ...
                   fullfile(Basedir,'Sim_12_results','30_subjects','Sim_12_30_subjects.mat'), ...
                   fullfile(Basedir,'Sim_12_results','60_subjects','Sim_12_60_subjects.mat'), ...
                   fullfile(Basedir,'Sim_12_results','120_subjects','Sim_12_120_subjects.mat'), ...
                   fullfile(Basedir,'Sim_12_results','240_subjects','Sim_12_240_subjects.mat'), ...
                   fullfile(Basedir,'Sim_12_results','480_subjects','Sim_12_480_subjects.mat')};

                   
               
sim_results_mat_dim = size(sim_results_mat);

nominal_levels      = [80, 90, 95];
nominal_prct_levels = nominal_levels/100;
nominal_levels_dim  = size(nominal_levels);

result = load(sim_results_mat{1});
nRlz          = result.nRlz;

std_error_vector = zeros(nominal_levels_dim);
sim_covering_levels_and_subs = zeros([3 5 12 3]);

for i = 1:nominal_levels_dim(2)
    i
    std_error = sqrt((nominal_prct_levels(i)*(1 - nominal_prct_levels(i)))/nRlz);
    std_error_vector(i) = std_error; 
 
    for j = 1:sim_results_mat_dim(1)
        for k = 1:sim_results_mat_dim(2)
            temp = load(char(sim_results_mat(j,k)));
            raw_volume_prct_store               = sprintf('upper_contour_observed_%d_volume_prct_store', nominal_levels(i));
            raw_subset_success                  = sprintf('subset_success_vector_raw_%d_alternate', nominal_levels(i));
            raw_sensitivity_result              = (temp.(raw_volume_prct_store)'*temp.(raw_subset_success))/sum(temp.(raw_subset_success));
            observed_volume_prct_store          = sprintf('upper_contour_observed_%d_volume_prct_store', nominal_levels(i));
            observed_subset_success             = sprintf('subset_success_vector_observed_%d_alternate', nominal_levels(i));
            observed_sensitivity_result         = (temp.(observed_volume_prct_store)'*temp.(observed_subset_success))/sum(temp.(observed_subset_success));
            nSubj                               = sprintf('nSubj');
            sim_covering_levels_and_subs(1,k,j,i) = raw_sensitivity_result;
            sim_covering_levels_and_subs(2,k,j,i) = observed_sensitivity_result;
            sim_covering_levels_and_subs(3,k,j,i) = temp.(nSubj);
        end
    end
end

results_params = struct('nom_80_results', struct('nominal_level', nominal_levels(1), ...
                                                 'nominal_prct_level', nominal_prct_levels(1), ...
                                                 'std_error', std_error_vector(1), ...
                                                 'met_1_sig_1_std_1_results', sim_covering_levels_and_subs(:,:,1,1),  ...
                                                 'met_1_sig_1_std_2_results', sim_covering_levels_and_subs(:,:,2,1),  ...
                                                 'met_2_sig_1_std_1_results', sim_covering_levels_and_subs(:,:,3,1),  ...
                                                 'met_2_sig_1_std_2_results', sim_covering_levels_and_subs(:,:,4,1),  ...
                                                 'met_3_sig_1_std_1_results', sim_covering_levels_and_subs(:,:,5,1),  ...
                                                 'met_3_sig_1_std_2_results', sim_covering_levels_and_subs(:,:,6,1),  ...
                                                 'met_1_sig_2_std_1_results', sim_covering_levels_and_subs(:,:,7,1),  ...
                                                 'met_1_sig_2_std_2_results', sim_covering_levels_and_subs(:,:,8,1),  ...
                                                 'met_2_sig_2_std_1_results', sim_covering_levels_and_subs(:,:,9,1),  ...
                                                 'met_2_sig_2_std_2_results', sim_covering_levels_and_subs(:,:,10,1),  ...
                                                 'met_3_sig_2_std_1_results', sim_covering_levels_and_subs(:,:,11,1),  ...
                                                 'met_3_sig_2_std_2_results', sim_covering_levels_and_subs(:,:,12,1)),  ...
                        'nom_90_results', struct('nominal_level', nominal_levels(2), ...
                                                 'nominal_prct_level', nominal_prct_levels(2), ...
                                                 'std_error', std_error_vector(2), ...
                                                 'met_1_sig_1_std_1_results', sim_covering_levels_and_subs(:,:,1,2),  ...
                                                 'met_1_sig_1_std_2_results', sim_covering_levels_and_subs(:,:,2,2),  ...
                                                 'met_2_sig_1_std_1_results', sim_covering_levels_and_subs(:,:,3,2),  ...
                                                 'met_2_sig_1_std_2_results', sim_covering_levels_and_subs(:,:,4,2),  ...
                                                 'met_3_sig_1_std_1_results', sim_covering_levels_and_subs(:,:,5,2),  ...
                                                 'met_3_sig_1_std_2_results', sim_covering_levels_and_subs(:,:,6,2),  ...
                                                 'met_1_sig_2_std_1_results', sim_covering_levels_and_subs(:,:,7,2),  ...
                                                 'met_1_sig_2_std_2_results', sim_covering_levels_and_subs(:,:,8,2),  ...
                                                 'met_2_sig_2_std_1_results', sim_covering_levels_and_subs(:,:,9,2),  ...
                                                 'met_2_sig_2_std_2_results', sim_covering_levels_and_subs(:,:,10,2),  ...
                                                 'met_3_sig_2_std_1_results', sim_covering_levels_and_subs(:,:,11,2),  ...
                                                 'met_3_sig_2_std_2_results', sim_covering_levels_and_subs(:,:,12,2)),  ...
                        'nom_95_results', struct('nominal_level', nominal_levels(3), ...
                                                 'nominal_prct_level', nominal_prct_levels(3), ...
                                                 'std_error', std_error_vector(3), ...
                                                 'met_1_sig_1_std_1_results', sim_covering_levels_and_subs(:,:,1,3),  ...
                                                 'met_1_sig_1_std_2_results', sim_covering_levels_and_subs(:,:,2,3),  ...
                                                 'met_2_sig_1_std_1_results', sim_covering_levels_and_subs(:,:,3,3),  ...
                                                 'met_2_sig_1_std_2_results', sim_covering_levels_and_subs(:,:,4,3),  ...
                                                 'met_3_sig_1_std_1_results', sim_covering_levels_and_subs(:,:,5,3),  ...
                                                 'met_3_sig_1_std_2_results', sim_covering_levels_and_subs(:,:,6,3),  ...
                                                 'met_1_sig_2_std_1_results', sim_covering_levels_and_subs(:,:,7,3),  ...
                                                 'met_1_sig_2_std_2_results', sim_covering_levels_and_subs(:,:,8,3),  ...
                                                 'met_2_sig_2_std_1_results', sim_covering_levels_and_subs(:,:,9,3),  ...
                                                 'met_2_sig_2_std_2_results', sim_covering_levels_and_subs(:,:,10,3),  ...
                                                 'met_3_sig_2_std_1_results', sim_covering_levels_and_subs(:,:,11,3),  ...
                                                 'met_3_sig_2_std_2_results', sim_covering_levels_and_subs(:,:,12,3))  ...                                                   
                        );
                    
filename = fullfile(outdir, '2DSensitivityResults.mat');
save(filename,'results_params');

